"use client"

import { useMemo, useState } from "react"
import { Minus, PackageOpen, Plus, Send } from "lucide-react"
import type { UmkmProduct } from "@/types"
import { PaginationControls } from "@/components/ui/pagination-controls"

const rupiah = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 })

export function UmkmOrderPanel({ businessName, whatsapp, products }: { businessName: string; whatsapp: string; products: UmkmProduct[] }) {
  const [quantities, setQuantities] = useState<Record<string, number>>({}), [choices, setChoices] = useState<Record<string, string>>({}), [page, setPage] = useState(1)
  const selected = useMemo(() => products.flatMap((product) => (product.variants.length ? product.variants : [{ name: "", price: product.price }]).filter((variant) => quantities[`${product.id}:${variant.name}`]).map((variant) => ({ product, variant, quantity: quantities[`${product.id}:${variant.name}`] }))), [products, quantities])
  const total = selected.reduce((sum, item) => sum + item.variant.price * item.quantity, 0), perPage = 8, totalPages = Math.max(1, Math.ceil(products.length / perPage)), visible = products.slice((Math.min(page, totalPages) - 1) * perPage, Math.min(page, totalPages) * perPage)
  const change = (key: string, amount: number) => setQuantities((current) => ({ ...current, [key]: Math.max(0, (current[key] ?? 0) + amount) }))
  const order = () => { const number = whatsapp.replace(/\D/g, "").replace(/^0/, "62"), lines = selected.map(({ product, variant, quantity }) => `- ${product.name}${variant.name ? ` (${variant.name})` : ""} × ${quantity} = ${rupiah.format(variant.price * quantity)}`); window.open(`https://wa.me/${number}?text=${encodeURIComponent([`Halo ${businessName}, saya ingin memesan:`, "", ...lines, "", `Total: ${rupiah.format(total)}`].join("\n"))}`, "_blank", "noopener,noreferrer") }
  if (!products.length) return <section className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center"><PackageOpen className="mx-auto size-9 text-slate-400" /><h2 className="mt-3 text-lg font-black">Produk belum tersedia</h2></section>
  return <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><section><div className="grid gap-4 sm:grid-cols-2">{visible.map((product) => { const variant = product.variants.find((item) => item.name === choices[product.id]) ?? product.variants[0] ?? { name: "", price: product.price }, key = `${product.id}:${variant.name}`; return <article key={product.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><img src={product.imageUrl} alt={product.name} className="aspect-[4/3] w-full object-cover" /><div className="p-5"><h2 className="font-black">{product.name}</h2><p className="mt-2 text-sm text-slate-600">{product.description}</p>{product.variants.length ? <label className="mt-4 block text-sm font-bold">Pilih varian<select value={variant.name} onChange={(event) => setChoices((current) => ({ ...current, [product.id]: event.target.value }))} className="mt-1 w-full rounded-xl border p-2">{product.variants.map((item) => <option key={item.name} value={item.name}>{item.name} — {rupiah.format(item.price)}</option>)}</select></label> : null}<p className="mt-4 text-lg font-black text-emerald-800">{rupiah.format(variant.price)}</p><div className="mt-4 flex justify-between"><span>Jumlah</span><div className="flex gap-2"><button onClick={() => change(key, -1)} disabled={!quantities[key]} className="rounded border p-2"><Minus className="size-4" /></button><output>{quantities[key] ?? 0}</output><button onClick={() => change(key, 1)} className="rounded bg-emerald-700 p-2 text-white"><Plus className="size-4" /></button></div></div></div></article>})}</div><PaginationControls className="mt-5" page={page} totalPages={totalPages} totalItems={products.length} pageSize={perPage} onPageChange={setPage} itemLabel="produk" /></section><aside className="h-fit rounded-3xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="text-xl font-black">Pesan via WhatsApp</h2>{selected.length ? <><ul className="mt-4 space-y-2">{selected.map(({ product, variant, quantity }) => <li key={`${product.id}:${variant.name}`}>{product.name}{variant.name ? ` (${variant.name})` : ""} × {quantity} — {rupiah.format(variant.price * quantity)}</li>)}</ul><p className="mt-4 font-black">Total: {rupiah.format(total)}</p><button onClick={order} className="mt-5 flex w-full justify-center gap-2 rounded-xl bg-emerald-700 p-3 text-white"><Send className="size-4" />Pesan sekarang</button></> : <p className="mt-4 text-sm">Pilih jumlah produk terlebih dahulu.</p>}</aside></div>
}
