import Link from "next/link"
import Image from "next/image"
import { ArrowRight, CalendarDays, Sparkles } from "lucide-react"
import type { NewsArticle } from "@/types"
import { Button } from "@/components/ui/button"
import { formatNewsDate } from "./news-card"

export function FeaturedNewsCard({ article }: { article: NewsArticle }) {
  return <article className="news-featured overflow-hidden border border-slate-200 bg-white shadow-[0_18px_45px_-32px_rgba(15,23,42,0.5)] md:grid md:grid-cols-[minmax(0,0.72fr)_minmax(0,1fr)]">{article.image_url ? <Link href={`/berita/${article.slug}`} className="group relative block min-h-72 overflow-hidden md:min-h-[440px]"><Image src={article.image_url} alt={`Ilustrasi ${article.title}`} fill priority sizes="(max-width: 1024px) 100vw, 48vw" className="object-cover transition duration-700 group-hover:scale-105"/></Link> : <div className="min-h-72 bg-[linear-gradient(135deg,#0a251f,#0f766e)] md:min-h-[440px]"/>}<div className="flex flex-col justify-center p-6 sm:p-8 lg:p-9"><div className="flex flex-wrap items-center gap-3 text-xs font-semibold"><span className="inline-flex items-center gap-1.5 bg-emerald-800 px-3 py-1.5 font-black uppercase tracking-[0.12em] text-white"><Sparkles size={13} /> {article.category || "Berita utama"}</span><time className="flex items-center gap-1.5 text-slate-500" dateTime={article.created_at}><CalendarDays size={14}/>{formatNewsDate(article.created_at)}</time></div><h2 className="mt-5 text-3xl font-black leading-[1.1] tracking-tight text-slate-950 sm:text-4xl"><Link href={`/berita/${article.slug}`} className="transition hover:text-emerald-800">{article.title}</Link></h2>{article.excerpt ? <p className="mt-4 line-clamp-5 text-sm leading-7 text-slate-600 sm:text-base">{article.excerpt}</p> : null}<Button asChild variant="ghost" className="mt-7 w-fit rounded-none px-0 text-emerald-800 hover:bg-transparent hover:text-emerald-950"><Link href={`/berita/${article.slug}`}>Baca selengkapnya <ArrowRight size={17}/></Link></Button></div></article>
}
