import Link from "next/link"
import Image from "next/image"
import type { NewsArticle } from "@/types"
import { Button } from "@/components/ui/button"
import { formatNewsDate } from "./news-card"
import { NewsArrowRightIcon, NewsCalendarIcon, NewsSparklesIcon } from "./news-icons"

export function FeaturedNewsCard({ article }: { article: NewsArticle }) {
  return <article className="news-featured group relative overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_70px_-38px_rgba(15,23,42,0.55)] sm:rounded-3xl md:grid md:grid-cols-[minmax(0,0.78fr)_minmax(0,1fr)]">{article.image_url ? <Link href={`/berita/${article.slug}`} className="news-hero-image relative block min-h-64 overflow-hidden sm:min-h-72 md:min-h-[460px]"><Image src={article.image_url} alt={`Ilustrasi ${article.title}`} fill priority sizes="(max-width: 767px) 100vw, (max-width: 1024px) 48vw, 48vw" className="object-cover transition duration-700 group-hover:scale-105"/><span aria-hidden="true" className="absolute inset-0 bg-gradient-to-t from-emerald-950/35 via-transparent to-transparent"/></Link> : <div className="min-h-64 bg-[linear-gradient(135deg,#0a251f,#0f766e)] sm:min-h-72 md:min-h-[460px]"/>}<div className="relative flex flex-col justify-center p-5 sm:p-8 lg:p-10"><span aria-hidden="true" className="absolute right-0 top-0 size-32 -translate-y-1/2 translate-x-1/2 rounded-full bg-emerald-100/70 blur-2xl"/><div className="relative"><div className="flex flex-wrap items-center gap-3 text-xs font-semibold"><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-800 px-3 py-1.5 font-black uppercase tracking-[0.12em] text-white shadow-sm"><NewsSparklesIcon size={13} /> {article.category || "Berita utama"}</span><time className="flex items-center gap-1.5 text-slate-500" dateTime={article.created_at}><NewsCalendarIcon size={14}/>{formatNewsDate(article.created_at)}</time></div><h2 className="mt-5 text-[clamp(1.75rem,8vw,2.25rem)] font-black leading-[1.08] tracking-tight text-slate-950"><Link href={`/berita/${article.slug}`} className="transition hover:text-emerald-800">{article.title}</Link></h2>{article.excerpt ? <p className="mt-4 line-clamp-5 text-sm leading-7 text-slate-600 sm:text-base">{article.excerpt}</p> : null}<div className="mt-6 flex flex-col gap-2 sm:mt-7 sm:flex-row sm:flex-wrap sm:items-center sm:gap-3"><Button asChild variant="ghost" className="w-fit rounded-none px-0 text-emerald-800 hover:bg-transparent hover:text-emerald-950"><Link href={`/berita/${article.slug}`}>Baca selengkapnya <NewsArrowRightIcon className="transition-transform duration-300 group-hover:translate-x-1" size={17}/></Link></Button></div></div></div></article>
}
