// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Runtime traffic may use the pooler. Prisma migrations need the direct
    // PostgreSQL connection when it is available.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
