"use client"
import Link from "next/link"
import { Menu, X, MapPinned } from "lucide-react"
import { useEffect, useState } from "react"
import type { NavigationItem } from "@/types"

const navigation: NavigationItem[] = [{ label: "Beranda", href: "/" }, { label: "Profil", href: "/profil" }, { label: "Data Desa", href: "/data-desa" }, { label: "Berita", href: "/berita" }, { label: "Layanan", href: "/layanan" }, { label: "Aduan", href: "/aduan" }]
export function Navbar() { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); useEffect(() => { const listener = () => setScrolled(window.scrollY > 16); listener(); window.addEventListener("scroll", listener); return () => window.removeEventListener("scroll", listener) }, []);
 return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${scrolled || open ? "border-b border-slate-200/70 bg-white/90 shadow-sm backdrop-blur-xl" : "bg-transparent"}`}><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-3" aria-label="Beranda Desa Kedungrejo"><span className="grid size-11 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-emerald-600 text-white shadow-lg shadow-blue-600/20"><MapPinned size={23}/></span><span><b className="block text-sm text-slate-900">DESA KEDUNGREJO</b><small className="text-xs font-medium text-slate-500">Kabupaten Banyuwangi</small></span></Link><nav className="hidden items-center gap-6 lg:flex">{navigation.map(item => <Link key={item.href} href={item.href} className="text-sm font-semibold text-slate-600 transition hover:text-blue-600">{item.label}</Link>)}<Link href="/admin" className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-blue-600">Portal Admin</Link></nav><button onClick={() => setOpen(!open)} aria-label="Buka menu navigasi" className="grid size-12 place-items-center rounded-xl text-slate-700 lg:hidden">{open ? <X/> : <Menu/>}</button></div>{open && <nav className="border-t border-slate-100 bg-white px-5 pb-5 lg:hidden">{navigation.map(item => <Link onClick={() => setOpen(false)} key={item.href} href={item.href} className="block rounded-xl px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-blue-50 hover:text-blue-600">{item.label}</Link>)}<Link href="/admin" className="mt-2 block rounded-xl bg-slate-900 px-4 py-3 text-center text-sm font-bold text-white">Portal Admin</Link></nav>}</header> }
