import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { PaginationControls } from "@/components/ui/pagination-controls"
import { BrowserlessSelect } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"
import { AlertIcon, CheckIcon, CloudIcon, DeleteIcon, MapIcon, MegaphoneIcon, PlusIcon, ShieldIcon, WavesIcon } from "@/components/bencana/admin-disaster-icons"
import { typeLabels, type DisasterStatus, type LocationDraft, type LocationType, locationsPerPage } from "@/components/bencana/admin-disaster-types"

const statusOptions = [
  { value: "auto", title: "Otomatis", description: "Ikuti pembaruan cuaca", icon: CloudIcon, active: "border-sky-400 bg-sky-50 text-sky-950 ring-sky-200", iconClass: "bg-sky-100 text-sky-700" },
  { value: "aman", title: "Aman", description: "Kondisi lapangan kondusif", icon: CheckIcon, active: "border-emerald-500 bg-emerald-50 text-emerald-950 ring-emerald-200", iconClass: "bg-emerald-100 text-emerald-700" },
  { value: "waspada", title: "Waspada", description: "Hujan deras atau genangan", icon: AlertIcon, active: "border-amber-400 bg-amber-50 text-amber-950 ring-amber-200", iconClass: "bg-amber-100 text-amber-700" },
  { value: "bahaya", title: "Siaga banjir", description: "Luapan atau banjir kiriman", icon: ShieldIcon, active: "border-rose-500 bg-rose-50 text-rose-950 ring-rose-200", iconClass: "bg-rose-100 text-rose-700" },
] as const

export function DisasterOverview({ activeLocations, status }: { activeLocations: number; status: DisasterStatus }) {
  return <Card data-disaster-animate className="overflow-hidden border-slate-200/80 shadow-lg shadow-slate-200/40"><CardContent className="relative grid gap-5 p-5 sm:grid-cols-[1fr_auto] sm:items-center sm:p-6"><div data-disaster-pulse className="absolute -right-10 -top-12 size-40 rounded-full bg-emerald-100/70" /><div className="relative"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Pusat kendali</p><h2 className="mt-2 text-xl font-bold tracking-tight text-slate-950 sm:text-2xl">Status lapangan dalam satu pandangan</h2><p className="mt-1.5 max-w-xl text-sm leading-6 text-slate-500">Perubahan yang Anda simpan akan diperbarui pada peta dan pemberitahuan warga.</p></div><dl className="relative grid grid-cols-2 gap-3 sm:flex"><div className="rounded-2xl border border-slate-100 bg-slate-50 px-3 py-3 text-center sm:px-4"><dt className="text-[11px] font-semibold text-slate-500">titik aktif</dt><dd className="text-xl font-bold text-slate-950">{activeLocations}</dd></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 px-3 py-3 text-center sm:px-4"><dt className="text-[11px] font-semibold text-emerald-700">mode status</dt><dd className="text-xl font-bold text-emerald-800">{status === "auto" ? "API" : "Manual"}</dd></div></dl></CardContent></Card>
}

export function StatusSection({ value, onChange }: { value: DisasterStatus; onChange: (value: DisasterStatus) => void }) {
  return <section aria-labelledby="disaster-status-title"><Card data-disaster-animate><CardHeader><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-100 text-emerald-800"><WavesIcon className="size-5" /></span><div><CardTitle id="disaster-status-title">Mode status keamanan</CardTitle><CardDescription className="mt-1">Pilih status yang ditampilkan kepada warga.</CardDescription></div></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{statusOptions.map(({ value: option, title, description, icon: Icon, active, iconClass }) => <button key={option} type="button" aria-pressed={value === option} onClick={() => onChange(option)} className={cn("group rounded-2xl border p-4 text-left transition-all hover:-translate-y-0.5 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500", value === option ? `${active} ring-2` : "border-slate-200 bg-white text-slate-700")}><div className="flex justify-between"><span className={cn("grid size-9 place-items-center rounded-xl", iconClass)}><Icon className="size-4" /></span>{value === option ? <CheckIcon className="size-5" /> : null}</div><p className="mt-4 text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 opacity-70">{description}</p></button>)}</div></CardContent></Card></section>
}

export function AnnouncementSection({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <section aria-labelledby="disaster-announcement-title"><Card data-disaster-animate><CardHeader><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-amber-100 text-amber-800"><MegaphoneIcon className="size-5" /></span><div><CardTitle id="disaster-announcement-title">Pengumuman darurat</CardTitle><CardDescription className="mt-1">Pesan ini tampil pada pengumuman kesiapsiagaan warga.</CardDescription></div></div></CardHeader><CardContent><Textarea rows={4} value={value} onChange={(event) => onChange(event.target.value)} placeholder="Contoh: Warga diimbau mengamankan barang dan mengikuti arahan petugas." /></CardContent></Card></section>
}

export function LocationsSection({ locations, page, onPageChange, onAdd, onUpdate, onRemove }: { locations: LocationDraft[]; page: number; onPageChange: (page: number) => void; onAdd: () => void; onUpdate: (index: number, field: keyof LocationDraft, value: string | boolean) => void; onRemove: (index: number) => void }) {
  const totalPages = Math.max(1, Math.ceil(locations.length / locationsPerPage))
  const currentPage = Math.min(page, totalPages)
  const visible = locations.slice((currentPage - 1) * locationsPerPage, currentPage * locationsPerPage).map((location, offset) => ({ location, index: (currentPage - 1) * locationsPerPage + offset }))
  return <section aria-labelledby="disaster-locations-title"><Card data-disaster-animate><CardHeader className="flex-col items-stretch gap-4 space-y-0 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-sky-100 text-sky-800"><MapIcon className="size-5" /></span><div><CardTitle id="disaster-locations-title">Titik pada peta publik</CardTitle><CardDescription className="mt-1">Gunakan koordinat desimal, misalnya -7.1571 dan 112.1593.</CardDescription></div></div><Button type="button" variant="outline" size="sm" onClick={onAdd} className="w-full sm:w-auto"><PlusIcon />Tambah titik</Button></CardHeader><CardContent className="space-y-3">{visible.map(({ location, index }) => <LocationForm key={location.id ?? `new-${index}`} location={location} index={index} onUpdate={onUpdate} onRemove={onRemove} />)}{!locations.length ? <EmptyLocations onAdd={onAdd} /> : null}<PaginationControls page={currentPage} totalPages={totalPages} totalItems={locations.length} pageSize={locationsPerPage} onPageChange={onPageChange} itemLabel="titik peta" /></CardContent></Card></section>
}

function LocationForm({ location, index, onUpdate, onRemove }: { location: LocationDraft; index: number; onUpdate: (index: number, field: keyof LocationDraft, value: string | boolean) => void; onRemove: (index: number) => void }) {
  return <article data-location-card className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4 sm:p-5"><header className="mb-4 flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-900">Titik {index + 1}</h3><p className="text-xs text-slate-500">Data lokasi untuk peta kesiapsiagaan.</p></div><Button type="button" variant="ghost" size="sm" onClick={() => onRemove(index)} className="text-rose-700 hover:bg-rose-50 hover:text-rose-800"><DeleteIcon />Hapus</Button></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Field label="Nama lokasi"><Input value={location.name} onChange={(event) => onUpdate(index, "name", event.target.value)} required /></Field><Field label="Jenis titik"><BrowserlessSelect value={location.type} onChange={(event) => onUpdate(index, "type", event.target.value)}>{(Object.keys(typeLabels) as LocationType[]).map((type) => <option key={type} value={type}>{typeLabels[type]}</option>)}</BrowserlessSelect></Field><Field label="Latitude"><Input type="number" step="any" value={location.latitude} onChange={(event) => onUpdate(index, "latitude", event.target.value)} required /></Field><Field label="Longitude"><Input type="number" step="any" value={location.longitude} onChange={(event) => onUpdate(index, "longitude", event.target.value)} required /></Field></div><Field label="Keterangan" className="mt-4"><Textarea rows={2} value={location.description ?? ""} onChange={(event) => onUpdate(index, "description", event.target.value)} className="min-h-20" /></Field><Label className="mt-4 inline-flex cursor-pointer items-center gap-2"><input type="checkbox" checked={location.isActive} onChange={(event) => onUpdate(index, "isActive", event.target.checked)} className="size-4 accent-emerald-700" />Tampilkan di peta publik</Label></article>
}

function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <div className={className}><Label>{label}</Label><div className="mt-1.5">{children}</div></div> }
function EmptyLocations({ onAdd }: { onAdd: () => void }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-5 py-10 text-center"><MapIcon className="mx-auto size-7 text-slate-400" /><p className="mt-3 text-sm font-semibold text-slate-700">Belum ada titik peta</p><p className="mt-1 text-sm text-slate-500">Tambahkan titik evakuasi, posko, atau zona rawan.</p><Button type="button" variant="outline" size="sm" onClick={onAdd} className="mt-4"><PlusIcon />Tambah titik pertama</Button></div> }
