"use client"

import Link from "next/link"
import { Clock3, FileCheck2, Search } from "lucide-react"
import type { ServiceCatalogItem } from "@/lib/village-services"

export function VillageServiceCatalog({ services }: { services: ServiceCatalogItem[] }) {
  return <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => <article key={service.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><FileCheck2 className="size-9 text-emerald-700" /><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800"><Clock3 className="mr-1 inline size-3.5" />{service.estimatedTime}</span></div><h2 className="mt-5 text-xl font-black text-slate-950">{service.title}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{service.description}</p><p className="mt-5 text-xs font-bold uppercase tracking-wider text-slate-500">Persyaratan</p><ul className="mt-2 space-y-1 text-sm text-slate-600">{service.requirements.slice(0, 3).map((item) => <li key={item.id}>• {item.title}</li>)}</ul><Link href={`/layanan/${service.slug}`} className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-emerald-700 px-4 py-2 text-sm font-bold text-white hover:bg-emerald-800">Ajukan layanan</Link></article>)}</div><TrackingForm /></section>
}

function TrackingForm() { return <div className="mt-12 rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="flex items-center gap-3"><Search className="text-emerald-300" /><div><h2 className="text-xl font-black">Lacak pengajuan</h2><p className="mt-1 text-sm text-slate-300">Gunakan kode pengajuan dan nomor WhatsApp Anda.</p></div></div><form className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget, result = form.querySelector<HTMLParagraphElement>("[data-result]"); const response = await fetch("/api/layanan/lacak", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const data = await response.json(); if (result) result.textContent = response.ok ? `${data.submission.service}: ${data.submission.status}${data.submission.history.at(-1)?.note ? ` — ${data.submission.history.at(-1).note}` : ""}` : data.message }}><input required name="trackingCode" placeholder="Kode pengajuan" className="h-11 rounded-xl px-3 text-sm text-slate-900" /><input required name="whatsapp" type="tel" placeholder="Nomor WhatsApp" className="h-11 rounded-xl px-3 text-sm text-slate-900" /><button className="h-11 rounded-xl bg-emerald-400 px-5 text-sm font-black text-slate-950 hover:bg-emerald-300">Lacak</button><p data-result aria-live="polite" className="sm:col-span-3 text-sm text-emerald-100" /></form></div> }
