"use client"

import Link from "next/link"
import { ArrowUpRight, CheckCircle2, Clock3, Search, ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { SectionHeading } from "@/components/ui/section-heading"
import { VillageServiceMotion } from "@/components/layanan/village-service-motion"
import { getServiceIcon } from "@/lib/service-icons"
import type { ServiceCatalogItem } from "@/lib/village-services"

export function VillageServiceCatalog({ services }: { services: ServiceCatalogItem[] }) {
  return <VillageServiceMotion><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div className="service-catalog-heading"><SectionHeading eyebrow="Layanan administrasi" title="Urus kebutuhan desa tanpa bingung." description="Pilih layanan, siapkan berkas, lalu pantau prosesnya secara mandiri dari kode pengajuan." /></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => { const Icon = getServiceIcon(service.icon); return <Card key={service.id} className="service-catalog-card group flex min-h-[350px] flex-col overflow-hidden border-slate-200 bg-white/95 shadow-sm transition-shadow hover:shadow-xl hover:shadow-emerald-950/10"><CardHeader className="p-6 pb-3"><div className="flex items-start justify-between gap-4"><span className="service-card-icon grid size-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><Icon className="size-6" /></span><span className="inline-flex items-center gap-1 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-800"><Clock3 className="size-3.5" />{service.estimatedTime}</span></div><CardTitle className="mt-5 text-xl font-black leading-snug group-hover:text-emerald-700">{service.title}</CardTitle><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{service.description}</p></CardHeader><CardContent className="p-6 pt-2"><p className="text-[11px] font-black uppercase tracking-[.16em] text-slate-500">Persyaratan utama</p><ul className="mt-3 space-y-2">{service.requirements.slice(0, 3).map((item) => <li key={item.id} className="flex items-start gap-2 text-sm leading-5 text-slate-600"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" />{item.title}</li>)}</ul></CardContent><CardFooter className="mt-auto p-6 pt-0"><Button asChild className="w-full"><Link href={`/layanan/${service.slug}`}>Ajukan layanan <ArrowUpRight /></Link></Button></CardFooter></Card> })}</div><TrackingForm /></section></VillageServiceMotion>
}

function TrackingForm() {
  return <section className="service-tracking-panel relative mt-14 overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white shadow-2xl shadow-slate-950/15 sm:mt-20 sm:p-9"><span aria-hidden className="service-tracking-glow absolute -right-16 -top-16 size-56 rounded-full bg-emerald-400/20 blur-3xl" /><div className="relative"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-emerald-400/15 text-emerald-300"><Search className="size-6" /></span><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Transparan & mudah</p><h2 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">Lacak pengajuan</h2><p className="mt-2 text-sm leading-6 text-slate-300">Masukkan kode pengajuan dan nomor WhatsApp yang dipakai saat mengajukan.</p></div></div><form className="mt-6 grid gap-3 lg:grid-cols-[1fr_1fr_auto]" onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget, result = form.querySelector<HTMLParagraphElement>("[data-result]"); const response = await fetch("/api/layanan/lacak", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const data = await response.json(); if (result) result.textContent = response.ok ? `${data.submission.service}: ${data.submission.status}${data.submission.history.at(-1)?.note ? ` — ${data.submission.history.at(-1).note}` : ""}` : data.message }}><input required name="trackingCode" placeholder="Contoh: KDR-2026-AB12CD34" className="h-14 rounded-xl border border-slate-300 bg-white px-4 text-sm font-medium text-slate-950 outline-none placeholder:text-slate-500 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-300/25" /><input required name="whatsapp" type="tel" placeholder="Nomor WhatsApp" className="h-14 rounded-xl border border-slate-300 bg-white px-4 text-sm font-medium text-slate-950 outline-none placeholder:text-slate-500 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-300/25" /><Button type="submit" size="lg" className="h-14 bg-emerald-400 text-slate-950 hover:bg-emerald-300">Lacak sekarang <ArrowUpRight /></Button><p data-result aria-live="polite" className="lg:col-span-3 text-sm font-medium text-emerald-100" /></form><p className="mt-5 flex items-center gap-2 text-xs font-semibold text-slate-400"><ShieldCheck className="size-4 text-emerald-300" />Data pelacakan hanya dapat diakses dengan kode dan nomor WhatsApp yang sesuai.</p></div></section>
}
