import Link from "next/link"
import { BarChart3, ChevronRight, MessageSquare, Newspaper, ShieldAlert, Store, Users, type LucideIcon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import type { AdminMetric } from "@/lib/admin-data"

const metricStyles: Record<AdminMetric["key"], { icon: LucideIcon; tone: string }> = { complaints: { icon: MessageSquare, tone: "bg-amber-50 text-amber-700" }, population: { icon: Users, tone: "bg-violet-50 text-violet-700" }, content: { icon: Newspaper, tone: "bg-emerald-50 text-emerald-700" }, umkm: { icon: Store, tone: "bg-sky-50 text-sky-700" } }
const quickLinks: { title: string; description: string; href: string; icon: LucideIcon; accent: string }[] = [{ title: "Kelola Infografis", description: "Perbarui statistik dan data penduduk desa.", href: "/admin/infografis", icon: BarChart3, accent: "bg-sky-100 text-sky-700" }, { title: "Kelola UMKM", description: "Atur profil usaha, produk, dan katalog UMKM.", href: "/admin/umkm", icon: Store, accent: "bg-amber-100 text-amber-700" }, { title: "Status Bencana", description: "Kelola peringatan darurat dan kondisi cuaca.", href: "/admin/bencana", icon: ShieldAlert, accent: "bg-rose-100 text-rose-700" }, { title: "Konten Halaman", description: "Edit hero dan section halaman publik.", href: "/admin/konten", icon: Newspaper, accent: "bg-emerald-100 text-emerald-700" }]

export function AdminMetricGrid({ metrics }: { metrics: AdminMetric[] }) { return <section data-admin-reveal aria-label="Ringkasan data CMS" className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ key, value, label, detail }) => { const { icon: Icon, tone } = metricStyles[key]; return <Card data-admin-card key={key} className="border-slate-200/80 transition-shadow hover:shadow-lg"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><span data-admin-card-icon className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" aria-hidden="true" /></span><span className="max-w-32 rounded-full bg-slate-100 px-2.5 py-1 text-right text-[11px] font-bold leading-4 text-slate-600">{detail}</span></div><dl className="mt-5"><dd className="text-3xl font-black tracking-tight text-slate-950">{value}</dd><dt className="mt-1 text-sm font-semibold text-slate-600">{label}</dt></dl></CardContent></Card> })}</section> }
export function AdminQuickLinks() { return <section data-admin-reveal aria-labelledby="akses-cepat-title" className="mt-6"><div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Akses cepat</p><h2 id="akses-cepat-title" className="mt-1 text-xl font-black text-slate-950">Modul pengelolaan</h2></div><Button variant="ghost" size="sm" asChild><Link href="/admin/modul">Lihat semua <ChevronRight /></Link></Button></div><nav aria-label="Akses cepat modul CMS" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{quickLinks.map(({ icon: Icon, title, description, href, accent }) => <Link data-admin-card key={title} href={href} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition-shadow hover:shadow-lg"><span data-admin-card-icon className={`grid h-11 w-11 place-items-center rounded-xl ${accent}`}><Icon className="h-5 w-5" aria-hidden="true" /></span><h3 className="mt-5 font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-emerald-700">Buka modul <ChevronRight data-admin-card-arrow className="h-4 w-4" aria-hidden="true" /></span></Link>)}</nav></section> }
