import Link from "next/link"
import { BarChart3, ChevronRight, ClipboardList, FileText, MessageSquare, Newspaper, ShieldAlert, Store, Users, type LucideIcon } from "lucide-react"
import { CardContent } from "@/components/ui/card"
import type { AdminActivity, AdminAttentionGroup, AdminMetric } from "@/lib/admin-data"

const metricStyles: Record<AdminMetric["key"], { icon: LucideIcon; tone: string }> = { complaints: { icon: MessageSquare, tone: "bg-amber-50 text-amber-700" }, population: { icon: Users, tone: "bg-violet-50 text-violet-700" }, content: { icon: Newspaper, tone: "bg-emerald-50 text-emerald-700" }, umkm: { icon: Store, tone: "bg-sky-50 text-sky-700" }, services: { icon: FileText, tone: "bg-emerald-50 text-emerald-700" } }
const attentionStyles: Record<AdminAttentionGroup["key"], { icon: LucideIcon; tone: string }> = { complaints: { icon: MessageSquare, tone: "bg-amber-50 text-amber-700" }, services: { icon: ClipboardList, tone: "bg-emerald-50 text-emerald-700" }, drafts: { icon: Newspaper, tone: "bg-sky-50 text-sky-700" } }
const quickLinks: { title: string; description: string; href: string; icon: LucideIcon; accent: string }[] = [
  { title: "Layanan & Pengajuan", description: "Kelola jenis layanan dan pengajuan administrasi warga.", href: "/admin/layanan", icon: FileText, accent: "bg-emerald-100 text-emerald-700" },
  { title: "Kelola Aduan", description: "Tinjau laporan warga dan perbarui penanganannya.", href: "/admin/aduan", icon: MessageSquare, accent: "bg-amber-100 text-amber-700" },
  { title: "Kelola Berita", description: "Tulis, simpan draft, dan publikasikan berita desa.", href: "/admin/berita", icon: Newspaper, accent: "bg-sky-100 text-sky-700" },
  { title: "Kelola UMKM", description: "Atur profil usaha, produk, dan katalog UMKM.", href: "/admin/umkm", icon: Store, accent: "bg-violet-100 text-violet-700" },
  { title: "Status Bencana", description: "Kelola peringatan darurat dan kondisi cuaca.", href: "/admin/bencana", icon: ShieldAlert, accent: "bg-rose-100 text-rose-700" },
  { title: "Tampilan Halaman", description: "Edit hero dan konten statis halaman publik.", href: "/admin/konten", icon: Newspaper, accent: "bg-emerald-100 text-emerald-700" },
]

export function AdminAttentionPanel({ attention = [] }: { attention?: AdminAttentionGroup[] }) {
  return <section data-admin-reveal aria-labelledby="perlu-ditindaklanjuti-title" className="mt-5 rounded-[28px] border border-emerald-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Prioritas operator</p><h2 id="perlu-ditindaklanjuti-title" className="mt-1 text-xl font-black text-slate-950">Perlu ditindaklanjuti</h2></div><p className="text-sm font-medium text-slate-500">Aduan, pengajuan, dan konten yang belum selesai.</p></div><div className="mt-5 grid gap-4 xl:grid-cols-3">{attention.map((group) => { const { icon: Icon, tone } = attentionStyles[group.key]; return <article key={group.key} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-start justify-between gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" aria-hidden="true" /></span><span className="rounded-full bg-white px-3 py-1 text-sm font-black text-slate-950 shadow-sm">{group.count}</span></div><h3 className="mt-4 font-black text-slate-950">{group.label}</h3><p className="mt-1 text-sm leading-5 text-slate-500">{group.description}</p><div className="mt-4 min-h-20 space-y-2">{group.items.length ? group.items.map((item) => <div key={item.id} className="rounded-xl bg-white px-3 py-2"><div className="flex items-start justify-between gap-2"><p className="line-clamp-1 text-sm font-bold text-slate-800">{item.title}</p><span className="shrink-0 rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-slate-600">{item.status}</span></div><p className="mt-1 truncate text-xs text-slate-500">{item.meta}</p></div>) : <p className="rounded-xl border border-dashed border-slate-200 bg-white px-3 py-4 text-center text-sm text-slate-500">Tidak ada yang perlu ditangani.</p>}</div><Link href={group.href} className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-emerald-700 hover:text-emerald-800">Buka pengelolaan <ChevronRight className="h-4 w-4" aria-hidden="true" /></Link></article> })}</div></section>
}

export function AdminMetricGrid({ metrics = [] }: { metrics?: AdminMetric[] }) { return <section data-admin-reveal aria-label="Ringkasan data CMS" className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(({ key, value, label, detail, href }) => { const { icon: Icon, tone } = metricStyles[key]; return <Link data-admin-card key={key} href={href} className="rounded-2xl border border-slate-200/80 bg-white transition-shadow hover:shadow-lg"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><span data-admin-card-icon className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" aria-hidden="true" /></span><span className="max-w-32 rounded-full bg-slate-100 px-2.5 py-1 text-right text-[11px] font-bold leading-4 text-slate-600">{detail}</span></div><dl className="mt-5"><dd className="text-3xl font-black tracking-tight text-slate-950">{value}</dd><dt className="mt-1 text-sm font-semibold text-slate-600">{label}</dt></dl></CardContent></Link> })}</section> }

export function AdminActivityPanel({ activity = [] }: { activity?: AdminActivity[] }) { const maximum = Math.max(1, ...activity.map((item) => item.value)); const colors = { amber: "bg-amber-500", emerald: "bg-emerald-600", sky: "bg-sky-600" }; return <section data-admin-reveal aria-labelledby="aktivitas-30-hari-title" className="mt-6 rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Pantauan singkat</p><h2 id="aktivitas-30-hari-title" className="mt-1 text-xl font-black text-slate-950">Aktivitas 30 hari terakhir</h2></div><BarChart3 className="h-6 w-6 text-emerald-700" aria-hidden="true" /></div><div className="mt-6 grid gap-5 md:grid-cols-3">{activity.map((item) => <div key={item.key}><div className="flex items-end justify-between gap-3"><p className="text-sm font-semibold text-slate-600">{item.label}</p><b className="text-2xl font-black text-slate-950">{item.value}</b></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100" role="img" aria-label={`${item.label}: ${item.value} dalam 30 hari terakhir`}><div className={`h-full min-w-0 rounded-full ${colors[item.color]}`} style={{ width: `${(item.value / maximum) * 100}%` }} /></div></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Jumlah dihitung dari data yang dibuat atau diterbitkan dalam 30 hari terakhir.</p></section> }

export function AdminQuickLinks() { return <section data-admin-reveal aria-labelledby="akses-cepat-title" className="mt-6"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Akses cepat</p><h2 id="akses-cepat-title" className="mt-1 text-xl font-black text-slate-950">Modul pengelolaan</h2></div><nav aria-label="Akses cepat modul CMS" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{quickLinks.map(({ icon: Icon, title, description, href, accent }) => <Link data-admin-card key={title} href={href} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition-shadow hover:shadow-lg"><span data-admin-card-icon className={`grid h-11 w-11 place-items-center rounded-xl ${accent}`}><Icon className="h-5 w-5" aria-hidden="true" /></span><h3 className="mt-5 font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-emerald-700">Buka modul <ChevronRight data-admin-card-arrow className="h-4 w-4" aria-hidden="true" /></span></Link>)}</nav></section> }
