import type { CmsField, CmsItemField, CmsPageSettings } from "@/components/admin/cms-page-editor-types"

export const pageSettings: CmsPageSettings[] = [
  { slug: "home", href: "/", summary: "Hero dan teks pengantar pada beberapa bagian beranda.", heroFields: ["eyebrow", "title", "description", "image", "imagePosition"], sections: [{ key: "services", label: "Pengantar layanan", fields: ["eyebrow", "title", "description", "action", "href"] }, { key: "digital", label: "Desa digital", fields: ["eyebrow", "title", "description", "action", "href"], itemFields: ["title", "description"] }, { key: "news", label: "Pengantar berita", fields: ["eyebrow", "title", "description", "action", "href"] }, { key: "cta", label: "Ajakan di bawah", fields: ["eyebrow", "title"] }], manage: { label: "Layanan & Pengajuan", href: "/admin/layanan", description: "Kartu layanan dan statistik beranda diisi otomatis dari data layanan serta data desa." } },
  { slug: "profil", href: "/profil", summary: "Teks profil, sejarah, visi-misi, perangkat desa, dan peta wilayah.", heroFields: ["eyebrow", "title", "description"], sections: [{ key: "history", label: "Sejarah desa", fields: ["eyebrow", "title", "description", "image", "captionEyebrow", "captionTitle", "storyLine"], itemFields: ["title", "value", "description"] }, { key: "vision-mission", label: "Visi & misi", fields: ["eyebrow", "title", "description"], itemFields: ["title"] }, { key: "government-cta", label: "Ajakan perangkat desa", fields: ["eyebrow", "title", "description", "action", "href"] }, { key: "village-map", label: "Peta wilayah", fields: ["eyebrow", "title", "description", "action", "href"] }] },
  { slug: "struktur-perangkat-desa", href: "/profil/struktur-perangkat-desa", summary: "Hero dan gambar bagan organisasi perangkat desa.", heroFields: ["eyebrow", "title", "description", "image", "imagePosition"], sections: [{ key: "organization-chart", label: "Bagan organisasi", fields: ["title", "description", "image"], itemFields: ["title"] }] },
  { slug: "layanan", href: "/layanan", summary: "Hero halaman katalog layanan. Daftar layanan dikelola terpisah.", heroFields: ["eyebrow", "title", "description", "image", "imagePosition"], manage: { label: "Layanan & Pengajuan", href: "/admin/layanan", description: "Tambah, ubah, atau nonaktifkan layanan dari modul Layanan & Pengajuan." } },
  { slug: "aduan", href: "/aduan", summary: "Hero serta judul formulir dan riwayat aduan.", heroFields: ["eyebrow", "title", "description", "image", "imagePosition"], sections: [{ key: "complaint-form", label: "Form aduan", fields: ["title"] }, { key: "complaint-history", label: "Riwayat aduan", fields: ["title"] }], manage: { label: "Kelola Aduan", href: "/admin/aduan", description: "Daftar aduan warga dan status tindak lanjut dikelola dari modul Kelola Aduan." } },
  { slug: "arsip", href: "/arsip", summary: "Hero dan catatan singkat pada halaman arsip publik.", heroFields: ["eyebrow", "title", "description", "image", "imagePosition"], sections: [{ key: "notice", label: "Catatan arsip", fields: ["title"] }], manage: { label: "Arsip Dokumen", href: "/admin/arsip", description: "Tambah, ubah, atau unggah dokumen publik dari modul Arsip Dokumen." } },
  { slug: "peta-bencana", href: "/peta-bencana", summary: "Hero, banner bantuan darurat, serta peta lokasi bencana dan kalender iklim.", heroFields: ["eyebrow", "title", "description", "image", "imagePosition"], sections: [{ key: "emergency-assistance", label: "Banner bantuan darurat", fields: ["eyebrow", "title", "description"], itemFields: ["title", "href"] }], manage: { label: "Bencana & Cuaca", href: "/admin/bencana", description: "Kelola titik peta, status darurat, dan data cuaca dari modul Bencana & Cuaca." } },
  { slug: "infografis", href: "/infografis", summary: "Hero halaman infografis. Dashboard datanya dikelola terpisah.", heroFields: ["eyebrow", "title", "description", "image", "imagePosition"], manage: { label: "Infografis", href: "/admin/infografis", description: "Gunakan modul Infografis untuk memperbarui data kependudukan dan dashboard." } },
  { slug: "berita", href: "/berita", summary: "Berita dan tampilannya dikelola dari modul berita.", manage: { label: "Kelola Berita", href: "/admin/berita", description: "Tambah, edit, hapus artikel, kategori, dan gambar berita dari modul Kelola Berita." } },
]

export const fieldLabels: Record<CmsField, string> = { eyebrow: "Teks kecil di atas judul", title: "Judul", description: "Deskripsi", action: "Teks tombol", href: "Tujuan tombol / tautan", image: "Gambar", imagePosition: "Posisi gambar", captionEyebrow: "Teks kecil pada gambar", captionTitle: "Judul pada gambar", storyLine: "Kalimat bawah statistik" }
export const itemLabels: Record<CmsItemField, string> = { title: "Judul", description: "Deskripsi", value: "Nilai", detail: "Detail", href: "Tautan", image: "Gambar" }
