"use client"

import { useState } from "react"
import { HugeiconsIcon } from "@hugeicons/react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { settingsIcons } from "@/components/admin/settings/settings-icons"
import { SettingsSectionHeader } from "@/components/admin/settings/settings-section-header"
import { SettingsTextField } from "@/components/admin/settings/settings-text-field"
import type { SiteRedirectRule, SiteSettings } from "@/lib/site-settings"

const fields: Array<{ key: "villageName" | "district" | "regency" | "province" | "officeAddress" | "phone" | "email" | "serviceHours"; label: string; wide?: boolean }> = [
  { key: "villageName", label: "Nama desa", wide: true }, { key: "district", label: "Kecamatan" }, { key: "regency", label: "Kabupaten" }, { key: "province", label: "Provinsi" }, { key: "officeAddress", label: "Alamat kantor", wide: true }, { key: "phone", label: "Telepon / WhatsApp" }, { key: "email", label: "Email" }, { key: "serviceHours", label: "Jam pelayanan", wide: true },
]

const SectionHeading = SettingsSectionHeader
const Search = settingsIcons.search
const Link2 = settingsIcons.link
const Save = () => <HugeiconsIcon icon={settingsIcons.save} strokeWidth={1.8} aria-hidden="true" />


export function SystemSettingsManager({ initialSettings, initialRedirects }: { initialSettings: SiteSettings; initialRedirects: SiteRedirectRule[] }) {
  const [settings, setSettings] = useState(initialSettings)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState("")
  const [redirects, setRedirects] = useState(initialRedirects)
  const update = (key: keyof SiteSettings, value: string) => setSettings((current) => ({ ...current, [key]: value }))
  const save = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSaving(true); setMessage("")
    try {
      const response = await fetch("/api/admin/pengaturan", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...settings, redirects }) })
      const payload = await response.json()
      if (!response.ok) throw new Error(payload.message ?? "Pengaturan tidak dapat disimpan.")
      setSettings(payload.settings); setRedirects(payload.redirects ?? []); window.localStorage.setItem("cms-public-updated", `${Date.now()}`)
      const notice = "Pengaturan sistem berhasil disimpan dan langsung diterapkan."
      setMessage(notice); window.dispatchEvent(new CustomEvent("cms:notice", { detail: { message: notice, variant: "success" } }))
    } catch (error) { const notice = error instanceof Error ? error.message : "Pengaturan tidak dapat disimpan."; setMessage(notice); window.dispatchEvent(new CustomEvent("cms:notice", { detail: { message: notice, variant: "error" } })) } finally { setSaving(false) }
  }
  return <form onSubmit={save} className="mt-6 space-y-5" data-settings-form>
    <section data-settings-motion="hero" className="relative overflow-hidden rounded-3xl bg-slate-950 p-4 text-white shadow-xl shadow-slate-950/10 sm:p-6"><span data-settings-orb className="absolute -right-12 -top-14 size-48 rounded-full bg-emerald-400/20 blur-3xl" /><span data-settings-orb-secondary className="absolute -bottom-20 right-28 size-44 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-300 sm:text-xs sm:tracking-[.18em]">Pusat kontrol website</p><h2 className="mt-2 text-xl font-black tracking-tight sm:text-2xl">Semua pengaturan, satu tempat.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Perbarui informasi publik dan konfigurasi teknis, lalu simpan saat sudah siap.</p></div><div className="grid grid-cols-3 gap-1.5 text-center sm:gap-2"><div data-settings-stat className="min-w-0 rounded-xl border border-white/10 bg-white/[.07] px-2 py-2.5 sm:rounded-2xl sm:px-4 sm:py-3"><strong className="block text-base sm:text-lg">{redirects.length}</strong><span className="block truncate text-[10px] text-slate-400 sm:text-[11px]">Redirect</span></div><div data-settings-stat className="min-w-0 rounded-xl border border-white/10 bg-white/[.07] px-2 py-2.5 sm:rounded-2xl sm:px-4 sm:py-3"><strong className="block text-base sm:text-lg">{settings.footerLinks.length}</strong><span className="block truncate text-[10px] text-slate-400 sm:text-[11px]">Link footer</span></div><div data-settings-stat className="min-w-0 rounded-xl border border-white/10 bg-white/[.07] px-2 py-2.5 sm:rounded-2xl sm:px-4 sm:py-3"><strong className="block text-base text-emerald-300 sm:text-lg">{settings.allowIndexing ? "ON" : "OFF"}</strong><span className="block truncate text-[10px] text-slate-400 sm:text-[11px]">Indeks</span></div></div></div></section>
    <section aria-labelledby="settings-identity-title"><Card data-settings-motion className="overflow-hidden border-slate-200/80 shadow-sm"><SettingsSectionHeader id="settings-identity-title" icon={settingsIcons.building} title="Identitas & kontak desa" description="Tampil pada navigasi dan footer situs publik." /><CardContent><div className="grid gap-4 md:grid-cols-2">{fields.map((field) => <SettingsTextField key={field.key} id={field.key} label={field.label} required={field.key === "villageName"} value={settings[field.key] ?? ""} wide={field.wide} onChange={(value) => update(field.key, value)} />)}</div></CardContent></Card></section>
    <div className="grid gap-5 xl:grid-cols-2"><section aria-labelledby="settings-maintenance-title"><Card data-settings-motion className="border-amber-100 shadow-sm"><SettingsSectionHeader id="settings-maintenance-title" icon={settingsIcons.maintenance} title="Mode maintenance" description="Admin dan login tetap dapat diakses saat aktif." tone="amber" /><CardContent><Label className="flex cursor-pointer items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"><span><span className="block font-black text-slate-900">Aktifkan maintenance</span><span className="mt-1 block text-xs font-medium text-slate-500">Tutup sementara halaman publik.</span></span><input aria-label="Aktifkan mode maintenance" type="checkbox" checked={settings.maintenanceMode} onChange={(event) => setSettings((current) => ({ ...current, maintenanceMode: event.target.checked }))} className="peer sr-only" /><span className="relative h-7 w-12 rounded-full bg-slate-300 transition peer-checked:bg-amber-500 after:absolute after:left-1 after:top-1 after:size-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:after:translate-x-5" /></Label><div className="mt-4"><Label htmlFor="maintenanceMessage">Pesan maintenance</Label><Textarea id="maintenanceMessage" value={settings.maintenanceMessage} onChange={(event) => update("maintenanceMessage", event.target.value)} rows={3} className="mt-2 min-h-24" /></div></CardContent></Card></section><section aria-labelledby="settings-announcement-title"><Card data-settings-motion className="border-rose-100 shadow-sm"><SettingsSectionHeader id="settings-announcement-title" icon={settingsIcons.announcement} title="Pengumuman umum" description="Ditampilkan di bagian atas situs publik." tone="rose" /><CardContent><Label htmlFor="publicAnnouncement">Pesan pengumuman</Label><Textarea id="publicAnnouncement" value={settings.publicAnnouncement ?? ""} onChange={(event) => update("publicAnnouncement", event.target.value)} rows={5} className="mt-2 min-h-[152px]" /></CardContent></Card></section></div>
    <Card data-settings-motion className="border-sky-100 shadow-sm"><SectionHeading icon={Search} title="SEO & pencarian" description="Pengaturan global yang menjadi fallback setiap halaman publik." tone="sky" /><CardContent><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Label htmlFor="siteUrl">URL situs utama</Label><Input id="siteUrl" type="url" value={settings.siteUrl} placeholder="https://desa.example.go.id" onChange={(event) => update("siteUrl", event.target.value)} className="mt-2" /></div><div><Label htmlFor="siteTitle">Judul situs</Label><Input id="siteTitle" value={settings.siteTitle} onChange={(event) => update("siteTitle", event.target.value)} className="mt-2" /></div><div><Label htmlFor="siteDescription">Deskripsi situs</Label><Input id="siteDescription" value={settings.siteDescription} onChange={(event) => update("siteDescription", event.target.value)} className="mt-2" /></div><div className="md:col-span-2"><Label htmlFor="seoKeywords">Kata kunci <span className="font-medium text-slate-400">(pisahkan koma)</span></Label><Input id="seoKeywords" value={settings.seoKeywords.join(", ")} onChange={(event) => setSettings((current) => ({ ...current, seoKeywords: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) }))} className="mt-2" /></div><div><Label htmlFor="seoImageUrl">Gambar berbagi</Label><Input id="seoImageUrl" type="url" value={settings.seoImageUrl ?? ""} onChange={(event) => update("seoImageUrl", event.target.value)} className="mt-2" /></div><div><Label htmlFor="googleVerification">Verifikasi Google Search Console</Label><Input id="googleVerification" value={settings.googleVerification ?? ""} onChange={(event) => update("googleVerification", event.target.value)} className="mt-2" /></div></div><Label className="mt-5 flex cursor-pointer items-center gap-3 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4 text-emerald-950"><input type="checkbox" checked={settings.allowIndexing} onChange={(event) => setSettings((current) => ({ ...current, allowIndexing: event.target.checked }))} className="size-4 accent-emerald-700" />Izinkan mesin pencari mengindeks situs</Label></CardContent></Card>
    <Card data-settings-motion className="shadow-sm"><SectionHeading icon={Link2} title="Redirect URL" description="Gunakan path internal, misalnya /berita-lama ke /berita." tone="violet" /><CardContent><div className="space-y-3">{redirects.map((item, index) => <div key={item.id || index} data-settings-row className="grid gap-3 rounded-2xl border border-slate-100 bg-slate-50/70 p-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]"><Input aria-label={`Path asal redirect ${index + 1}`} value={item.source} onChange={(event) => setRedirects((current) => current.map((row, i) => i === index ? { ...row, source: event.target.value } : row))} placeholder="/url-lama" /><Input aria-label={`Path tujuan redirect ${index + 1}`} value={item.destination} onChange={(event) => setRedirects((current) => current.map((row, i) => i === index ? { ...row, destination: event.target.value } : row))} placeholder="/url-baru" /><Button type="button" variant="ghost" onClick={() => setRedirects((current) => current.filter((_, i) => i !== index))} className="w-full text-rose-700 hover:bg-rose-50 hover:text-rose-800 md:w-auto">Hapus</Button></div>)}</div><Button type="button" variant="outline" onClick={() => setRedirects((current) => [...current, { id: crypto.randomUUID(), source: "", destination: "" }])} className="mt-4 w-full sm:w-auto">Tambah redirect</Button></CardContent></Card>
    <div data-settings-save className="sticky bottom-2 z-10 flex flex-col gap-2 rounded-2xl border border-slate-200/80 bg-white/95 p-3 shadow-lg shadow-slate-900/10 backdrop-blur sm:bottom-4 sm:flex-row sm:flex-wrap sm:items-center sm:gap-3"><Button data-admin-action type="submit" disabled={saving} size="lg" className="w-full font-black sm:w-auto"><Save />{saving ? "Menyimpan..." : "Simpan semua pengaturan"}</Button><p className="text-center text-xs font-medium text-slate-500 sm:text-left">{message ? "Notifikasi hasil simpan ditampilkan di popup." : "Perubahan belum diterapkan sebelum disimpan."}</p></div>
  </form>
}
