import Link from "next/link"

import { ChevronRight, FileIcon, MessageIcon, NewsIcon } from "@/components/admin/dashboard-icons"
import { DashboardSectionHeading } from "@/components/admin/dashboard/section-heading"
import { Card } from "@/components/ui/card"
import type { AdminAttentionGroup } from "@/lib/admin-data"

const attentionStyles = { complaints: { icon: MessageIcon, tone: "bg-amber-50 text-amber-700" }, services: { icon: FileIcon, tone: "bg-emerald-50 text-emerald-700" }, drafts: { icon: NewsIcon, tone: "bg-sky-50 text-sky-700" } }

export function AdminAttentionPanel({ attention = [] }: { attention?: AdminAttentionGroup[] }) { return <section data-admin-reveal aria-labelledby="perlu-ditindaklanjuti-title" className="mt-5"><Card className="rounded-[28px] border-emerald-100 p-5 shadow-sm sm:p-6"><DashboardSectionHeading eyebrow="Prioritas operator" title="Perlu ditindaklanjuti" titleId="perlu-ditindaklanjuti-title" description="Aduan, pengajuan, dan konten yang belum selesai." /><ul className="mt-5 grid gap-4 xl:grid-cols-3">{attention.map((group) => { const { icon: Icon, tone } = attentionStyles[group.key]; return <li key={group.key}><article data-admin-card className="h-full rounded-2xl border border-slate-200 bg-slate-50/70 p-4 transition-shadow hover:shadow-md"><div className="flex items-start justify-between gap-3"><span data-admin-card-icon className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></span><data value={group.count} className="rounded-full bg-white px-3 py-1 text-sm font-black text-slate-950 shadow-sm">{group.count}</data></div><h3 className="mt-4 font-black text-slate-950">{group.label}</h3><p className="mt-1 text-sm leading-5 text-slate-500">{group.description}</p><div className="mt-4 min-h-20">{group.items.length ? <ul className="space-y-2">{group.items.map((item) => <li key={item.id} className="rounded-xl bg-white px-3 py-2"><div className="flex items-start justify-between gap-2"><p className="line-clamp-1 text-sm font-bold text-slate-800">{item.title}</p><span className="shrink-0 rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-slate-600">{item.status}</span></div><p className="mt-1 truncate text-xs text-slate-500">{item.meta}</p></li>)}</ul> : <p className="rounded-xl border border-dashed border-slate-200 bg-white px-3 py-4 text-center text-sm text-slate-500">Tidak ada yang perlu ditangani.</p>}</div><Link data-admin-action href={group.href} className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-emerald-700 hover:text-emerald-800">Buka pengelolaan <ChevronRight className="h-4 w-4" /></Link></article></li> })}</ul></Card></section> }
