"use client"

import { useMemo, useState } from "react"
import { Bar, Doughnut, Line } from "react-chartjs-2"
import { HeartPulse, MapPin, Search, UsersRound } from "lucide-react"

import "@/components/infografis/chartjs"
import { ChartCard, SectionHeader } from "./infographic-dashboard-ui"
import type { PublicElderlyHealth } from "@/lib/public-elderly-health"

function age(value: string) {
  const birthDate = new Date(value)
  const today = new Date()
  let result = today.getFullYear() - birthDate.getFullYear()
  if (today.getMonth() < birthDate.getMonth() || (today.getMonth() === birthDate.getMonth() && today.getDate() < birthDate.getDate())) result -= 1
  return result
}

export function MedicalData({ data }: { data: PublicElderlyHealth }) {
  const [section, setSection] = useState<"visual" | "profil" | "posyandu" | "anak" | "dashboard-anak">("visual")
  const [query, setQuery] = useState("")
  const [dusun, setDusun] = useState("")
  const filtered = useMemo(() => data.elderly.filter((person) => (!dusun || person.dusun === dusun) && (!query.trim() || person.fullName.toLocaleLowerCase("id-ID").includes(query.trim().toLocaleLowerCase("id-ID")))), [data.elderly, dusun, query])
  const diseaseChart = useMemo(() => ({ labels: data.diseaseSummary.map((item) => item.label), datasets: [{ label: "Lansia", data: data.diseaseSummary.map((item) => item.total), backgroundColor: "#047857", borderRadius: 8 }] }), [data.diseaseSummary])
  const hamletChart = useMemo(() => ({ labels: data.hamletSummary.map((item) => item.dusun.replace("Dusun ", "")), datasets: [{ label: "Lansia aktif", data: data.hamletSummary.map((item) => item.total), backgroundColor: "#0f766e", borderRadius: 8 }] }), [data.hamletSummary])
  const coverageChart = useMemo(() => ({ labels: ["Dengan penyakit tercatat", "Tanpa penyakit tercatat"], datasets: [{ data: [data.coverage.withDisease, data.coverage.withoutDisease], backgroundColor: ["#e11d48", "#10b981"], borderWidth: 0 }] }), [data.coverage])
  const diseaseHamletChart = useMemo(() => ({ labels: data.diseaseByHamlet.map((item) => item.disease), datasets: data.hamletSummary.map((item, index) => ({ label: item.dusun.replace("Dusun ", ""), data: data.diseaseByHamlet.map((disease) => disease.dusun[item.dusun] ?? 0), backgroundColor: ["#047857", "#0f766e", "#0d9488", "#34d399"][index % 4], borderRadius: 4 })) }), [data.diseaseByHamlet, data.hamletSummary])
  const attendanceChart = useMemo(() => ({ labels: [...data.posyandu.sessions].reverse().map((session) => session.name), datasets: [{ label: "Lansia hadir", data: [...data.posyandu.sessions].reverse().map((session) => session.attendance), backgroundColor: "#0f766e", borderRadius: 8 }] }), [data.posyandu.sessions])
  const childAttendanceChart = useMemo(() => ({ labels: [...data.childPosyandu.sessions].reverse().map((session) => session.name), datasets: [{ label: "Anak hadir", data: [...data.childPosyandu.sessions].reverse().map((session) => session.attendance), backgroundColor: "#2563eb", borderRadius: 8 }] }), [data.childPosyandu.sessions])
  const childTrendChart = useMemo(() => ({ labels: data.childDashboard.measurementTrend.map((item) => item.month), datasets: [{ label: "Rata-rata BB (kg)", data: data.childDashboard.measurementTrend.map((item) => item.weightKg), borderColor: "#047857", backgroundColor: "rgba(4,120,87,.12)", tension: .3 }, { label: "Rata-rata PB/TB (cm)", data: data.childDashboard.measurementTrend.map((item) => item.heightCm), borderColor: "#0f766e", backgroundColor: "rgba(15,118,110,.12)", tension: .3 }] }), [data.childDashboard.measurementTrend])
  const totalDiseases = data.diseaseSummary.reduce((total, item) => total + item.total, 0)

  return <section data-infographic-motion className="mt-6" aria-labelledby="medical-data-title">
    <SectionHeader tag="Kesehatan Warga" title={section === "visual" ? "Visualisasi Lansia & Penyakit" : section === "profil" ? "Profil Lansia" : section === "anak" ? "Profil Bayi & Balita" : section === "dashboard-anak" ? "Dashboard Anak & Balita" : "Kegiatan Posyandu"} subtitle={section === "visual" ? "Ringkasan data lansia aktif di Desa Kedungrejo. Hasil pemeriksaan dan alamat tidak dipublikasikan." : section === "profil" ? "Kartu profil lansia publik tanpa alamat dan hasil pemeriksaan." : section === "anak" ? "Profil anak yang ditampilkan hanya dengan persetujuan wali, tanpa data kesehatan maupun alamat." : section === "dashboard-anak" ? "Rekap tumbuh-kembang dan layanan KIA tanpa identitas anak maupun hasil pemeriksaan per orang." : "Jadwal dan rekap kehadiran posyandu tanpa identitas maupun hasil pemeriksaan warga."} />
    <div className="mt-6 flex flex-wrap gap-2 border-b border-slate-200 pb-4"><button type="button" onClick={() => setSection("visual")} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${section === "visual" ? "bg-emerald-700 text-white" : "border border-emerald-200 bg-white text-emerald-800"}`}>Visualisasi Kesehatan</button><button type="button" onClick={() => setSection("profil")} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${section === "profil" ? "bg-emerald-700 text-white" : "border border-emerald-200 bg-white text-emerald-800"}`}>Profil Lansia</button><button type="button" onClick={() => setSection("dashboard-anak")} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${section === "dashboard-anak" ? "bg-emerald-700 text-white" : "border border-emerald-200 bg-white text-emerald-800"}`}>Dashboard Anak</button><button type="button" onClick={() => setSection("anak")} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${section === "anak" ? "bg-emerald-700 text-white" : "border border-emerald-200 bg-white text-emerald-800"}`}>Profil Bayi & Balita</button><button type="button" onClick={() => setSection("posyandu")} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${section === "posyandu" ? "bg-emerald-700 text-white" : "border border-emerald-200 bg-white text-emerald-800"}`}>Kegiatan Posyandu</button></div>
    {section === "dashboard-anak" ? <section className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Anak aktif", value: data.childDashboard.metrics.totalChildren }, { label: "Sudah diperiksa", value: data.childDashboard.metrics.checkedChildren }, { label: "Kehadiran", value: `${data.childDashboard.metrics.attendanceRate}%` }, { label: "Sesi tercatat", value: data.childDashboard.metrics.sessionCount }].map((item) => <Metric key={item.label} icon={UsersRound} label={item.label} value={item.value} />)}</div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Tren pengukuran bulanan" description="Rata-rata agregat anak yang diperiksa"><div className="h-72">{data.childDashboard.measurementTrend.length ? <Line data={childTrendChart} options={{ responsive: true, maintainAspectRatio: false }} /> : <EmptyPublic />}</div></ChartCard><PublicSummary title="Perkembangan" rows={data.childDashboard.developmentSummary} /><PublicSummary title="Tindakan KIA" rows={data.childDashboard.interventionSummary} /><PublicSummary title="Kehadiran sesi anak" rows={data.childDashboard.sessionAttendance.map((item) => ({ label: item.name, total: item.attendance }))} /></div></section> : null}
    {section === "anak" ? <section className="mt-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.children.map((child) => <article key={child.id} className="rounded-3xl border border-emerald-100 bg-white p-5 shadow-sm"><span className="grid size-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><UsersRound className="size-5" /></span><h3 className="mt-4 text-lg font-black text-slate-900">{child.firstName}</h3><p className="mt-1 text-sm font-semibold text-slate-500">{child.dusun} · {child.ageMonths} bulan</p><span className="mt-4 inline-block rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800">Bayi & Balita</span></article>)}{!data.children.length ? <p className="rounded-3xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">Belum ada profil anak yang disetujui untuk dipublikasikan.</p> : null}</div></section> : null}
    {data.elderly.length && section === "visual" ? <><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={UsersRound} label="Lansia aktif" value={data.elderly.length} /><Metric icon={HeartPulse} label="Catatan penyakit aktif" value={totalDiseases} /><Metric icon={MapPin} label="Dusun terdata" value={data.hamletSummary.length} /></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><ChartCard title="Penyakit aktif terbanyak" description="Jumlah lansia per penyakit yang tercatat"><div className="h-72"><Bar data={diseaseChart} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} /></div></ChartCard><ChartCard title="Cakupan catatan penyakit" description="Perbandingan profil dengan dan tanpa penyakit tercatat"><div className="h-72"><Doughnut data={coverageChart} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { position: "bottom" } } }} /></div></ChartCard><ChartCard title="Sebaran lansia per dusun" description="Jumlah lansia aktif yang terdaftar"><div className="h-72"><Bar data={hamletChart} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} /></div></ChartCard><ChartCard title="Penyakit menurut dusun" description="Sebaran penyakit aktif pada setiap dusun"><div className="h-72"><Bar data={diseaseHamletChart} options={{ responsive: true, maintainAspectRatio: false, scales: { x: { stacked: true }, y: { stacked: true } } }} /></div></ChartCard></div></> : null}
    {data.elderly.length && section === "profil" ? <section className="mt-5" aria-labelledby="public-elderly-profile-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 id="public-elderly-profile-title" className="text-xl font-black text-slate-900">Profil Kartu Digital Lansia</h3><p className="mt-1 text-sm text-slate-500">Profil publik tanpa data pemeriksaan dan alamat.</p></div><p className="text-sm font-bold text-emerald-800">{filtered.length} profil</p></div><div className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_220px]"><label className="relative"><span className="sr-only">Cari nama lansia</span><Search className="absolute left-3 top-3 size-5 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama lansia" className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100" /></label><select value={dusun} onChange={(event) => setDusun(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700"><option value="">Semua dusun</option>{data.hamletSummary.map((item) => <option key={item.dusun}>{item.dusun}</option>)}</select></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((person) => <article key={person.id} className="rounded-3xl border border-emerald-100 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="grid size-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><UsersRound className="size-5" /></span><h4 className="mt-4 text-lg font-black text-slate-900">{person.fullName}</h4><p className="mt-1 text-sm font-semibold text-slate-500">{person.dusun} · {age(person.birthDate)} tahun</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800">Lansia</span></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Penyakit tercatat</p><div className="mt-2 flex flex-wrap gap-1.5">{person.diseases.length ? person.diseases.map((disease) => <span key={disease} className="rounded-full bg-rose-50 px-2.5 py-1 text-xs font-bold text-rose-700">{disease}</span>) : <span className="text-sm text-slate-400">Belum ada penyakit tercatat</span>}</div></div></article>)}{!filtered.length ? <p className="rounded-3xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">Profil lansia yang dicari belum tersedia.</p> : null}</div></section> : null}
    {section === "posyandu" ? <section className="mt-5 space-y-5"><article className="rounded-3xl border border-emerald-200 bg-emerald-50/60 p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Jadwal berikutnya</p>{data.posyandu.nextSession ? <><h3 className="mt-2 text-xl font-black text-slate-900">{data.posyandu.nextSession.name}</h3><p className="mt-2 text-sm text-slate-600">{new Intl.DateTimeFormat("id-ID", { dateStyle: "full" }).format(new Date(data.posyandu.nextSession.sessionDate))}</p></> : <p className="mt-2 text-sm text-slate-600">Belum ada jadwal posyandu mendatang yang dipublikasikan.</p>}</article>{data.posyandu.sessions.length ? <><ChartCard title="Kehadiran sesi posyandu" description="Jumlah lansia yang tercatat hadir pada setiap sesi"><div className="h-72"><Bar data={attendanceChart} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} /></div></ChartCard><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h3 className="font-black text-slate-900">Rekap sesi terbaru</h3></div><div className="divide-y divide-slate-100">{data.posyandu.sessions.map((session) => <div key={session.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-bold text-slate-900">{session.name}</p><p className="mt-1 text-sm text-slate-500">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(session.sessionDate))}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-black text-emerald-800">{session.attendance} hadir</span></div>)}</div></div></> : <div className="rounded-3xl border border-dashed border-emerald-200 bg-white p-10 text-center text-sm text-slate-500">Belum ada sesi posyandu yang dapat ditampilkan.</div>}</section> : null}
    {section === "posyandu" ? <section className="mt-8 space-y-5 border-t border-slate-200 pt-8"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Posyandu Anak</p><h3 className="mt-1 text-xl font-black text-slate-900">Kegiatan Bayi & Balita</h3><p className="mt-1 text-sm text-slate-500">Jadwal dan rekap kehadiran anak tanpa identitas maupun hasil pemeriksaan.</p></div><article className="rounded-3xl border border-blue-200 bg-blue-50/60 p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Jadwal berikutnya</p>{data.childPosyandu.nextSession ? <><h4 className="mt-2 text-xl font-black text-slate-900">{data.childPosyandu.nextSession.name}</h4><p className="mt-2 text-sm text-slate-600">{new Intl.DateTimeFormat("id-ID", { dateStyle: "full" }).format(new Date(data.childPosyandu.nextSession.sessionDate))}</p></> : <p className="mt-2 text-sm text-slate-600">Belum ada jadwal posyandu anak mendatang yang dipublikasikan.</p>}</article>{data.childPosyandu.sessions.length ? <><ChartCard title="Kehadiran sesi posyandu anak" description="Jumlah bayi dan balita yang tercatat hadir pada setiap sesi"><div className="h-72"><Bar data={childAttendanceChart} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} /></div></ChartCard><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h4 className="font-black text-slate-900">Rekap sesi anak terbaru</h4></div><div className="divide-y divide-slate-100">{data.childPosyandu.sessions.map((session) => <div key={session.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-bold text-slate-900">{session.name}</p><p className="mt-1 text-sm text-slate-500">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(session.sessionDate))}</p></div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-black text-blue-800">{session.attendance} hadir</span></div>)}</div></div></> : <div className="rounded-3xl border border-dashed border-blue-200 bg-white p-10 text-center text-sm text-slate-500">Belum ada sesi posyandu anak yang dapat ditampilkan.</div>}</section> : null}
    {(section === "visual" || section === "profil") && !data.elderly.length ? <div className="mt-6 rounded-3xl border border-dashed border-emerald-200 bg-white p-10 text-center"><HeartPulse className="mx-auto size-8 text-emerald-700" /><h3 className="mt-4 text-xl font-black text-slate-900">{section === "visual" ? "Belum ada data visualisasi kesehatan" : "Belum ada profil lansia publik"}</h3><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">{section === "visual" ? "Grafik akan muncul otomatis setelah data lansia aktif ditambahkan melalui modul Rekam Medis Lansia." : "Kartu profil akan muncul otomatis setelah data lansia aktif ditambahkan melalui modul Rekam Medis Lansia."}</p></div> : null}
  </section>
}

function Metric({ icon: Icon, label, value }: { icon: typeof UsersRound; label: string; value: number | string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="size-5" /></span><p className="mt-4 text-2xl font-black text-slate-900">{typeof value === "number" ? value.toLocaleString("id-ID") : value}</p><p className="mt-1 text-sm font-bold text-slate-600">{label}</p></article> }
function EmptyPublic() { return <p className="grid h-full place-items-center text-center text-sm text-slate-500">Belum ada pengukuran anak yang dapat direkap.</p> }
function PublicSummary({ title, rows }: { title: string; rows: { label: string; total: number }[] }) { return <ChartCard title={title} description="Rekap agregat tanpa identitas"><div className="space-y-2">{rows.length ? rows.map((row) => <div key={row.label} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-700"><span>{row.label}</span><b>{row.total.toLocaleString("id-ID")}</b></div>) : <EmptyPublic />}</div></ChartCard> }
