"use client"

import { useEffect, useState } from "react"
import { BarChart3, BriefcaseBusiness, GraduationCap, MapPinned, Users } from "lucide-react"

type Dashboard = { totals: { population: number; households: number; male: number; female: number }; ageGroups: { label: string; total: number }[]; hamlets: { label: string; total: number }[]; educations: { label: string; total: number }[]; occupations: { label: string; total: number }[] }
const formatter = new Intl.NumberFormat("id-ID")
function ListCard({ title, icon: Icon, rows }: { title: string; icon: typeof Users; rows: { label: string; total: number }[] }) { return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Icon className="size-5 text-emerald-700" /><h3 className="font-black text-slate-900">{title}</h3></div><div className="mt-4 space-y-3">{rows.map((row) => <div key={row.label}><div className="flex justify-between gap-3 text-sm font-semibold text-slate-700"><span>{row.label}</span><span>{formatter.format(row.total)}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${Math.min(100, rows.length ? row.total / Math.max(...rows.map((item) => item.total), 1) * 100 : 0)}%` }} /></div></div>)}</div></article> }

export function ResidentDashboard() {
  const [data, setData] = useState<Dashboard | null>(null)
  useEffect(() => { const load = () => void fetch("/api/infografis/penduduk", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then(setData).catch(() => setData(null)); load(); window.addEventListener("cms-content-updated", load); return () => window.removeEventListener("cms-content-updated", load) }, [])
  if (!data) return <p className="mt-6 text-sm font-medium text-slate-500">Memuat data penduduk...</p>
  const cards = [["Jumlah Penduduk", data.totals.population], ["Kepala Keluarga", data.totals.households], ["Laki-laki", data.totals.male], ["Perempuan", data.totals.female]]
  return <section className="mt-6" aria-labelledby="resident-dashboard-title"><header><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Data terkini</p><h2 id="resident-dashboard-title" className="mt-1 text-2xl font-black text-slate-900">Data & Infografis Desa</h2><p className="mt-2 text-sm leading-6 text-slate-600">Statistik dihitung otomatis dari data warga aktif tanpa menampilkan identitas pribadi.</p></header><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <article key={String(label)} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><Users className="size-5 text-emerald-700" /><p className="mt-4 text-3xl font-black text-slate-900">{formatter.format(Number(value))}</p><p className="mt-1 text-sm font-bold text-slate-600">{label}</p></article>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><ListCard title="Kelompok usia" icon={Users} rows={data.ageGroups} /><ListCard title="Sebaran per dusun" icon={MapPinned} rows={data.hamlets} /><ListCard title="Pendidikan terakhir" icon={GraduationCap} rows={data.educations} /><ListCard title="Mata pencaharian" icon={BriefcaseBusiness} rows={data.occupations} /></div></section>
}
